### ISSUE TITLE
Please provide option to add different keys for Same project.

### ISSUE THREAD

**Issue by phanikumarmss** [jenkinsci/google-oauth-plugin#12]
My concern here is to add different authentication keys for the same Project. Because I had a situation where I am supposed to use one authentication key for uploading files to Google Cloud Storage which don't have access to other services apart from Google Cloud Storage. While on the other hand, I have another key for the same project which I should use for running GCloud commands in another job. But when I am uploading the key with same project name my second private key is not getting uploaded as it has the same project name. It will be a great help to me if I could get some option to upload multiple keys for the same project.

**Comment by stephenashank** [comment]
This response is long overdue. After testing something today with configuration, I learned that the `projectId` or Project Name field is used for nothing more (within this plugin) than acting as the overall credential ID. As a result this field can be anything, allowing you to create multiple keys per project.

There is one case where I am aware of the project ID of the key being used outside this plugin, shown [here](https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/e40cb82f39ebe5cf28ec374e21863c7f2b3d38c1/src/main/java/com/google/jenkins/plugins/k8sengine/CredentialsUtil.java#L148). Sometimes, during configuration of a "Deploy to GKE" build step, if you are selecting the credentials that don't match a project ID and a project ID is not already chosen, the project ID dropdown will appear to populate with the first project ID available, but a verification error will still ask you to choose a project. To fix this, select the empty project entry from the drop down, then it will populate it without an error.

Otherwise, when using the credentials with our supported plugins (google-compute-engine-plugin, google-kubernetes-engine-plugin, google-storage-plugin) you are able to use that key with any project where the service account has the required permissions, so there aren't any checks against that project ID field on our end. A simple temporary solution would be to just change the label on that field to "Credential ID".

There's room for discussion for solutions like #42. Also, because project ID is only used in one case which provides a minor convenience (default to a potentially more relevant project instead of the first element in the project list), and a specific project is not needed to use the key, I think it would make sense to deprecate and remove this field, starting by removing the usage from the GKE plugin. Backwards compatibility will need to be taken into account, so that references to existing keys don't break, and to a lesser extent compatibility with plugins we don't maintain but which use this credentials type and might actually use the project ID. Feedback welcome.

**Comment by mruell** [comment]
Hi @rsandell !

I hope it's fine that I bump this old issue - let me know if not
We noticed that while the auth plugin does not use the projectId it is used by e.g. the [gcp upload plugin](https://www.jenkins.io/doc/pipeline/steps/google-storage-plugin/)

So we can't use different credentials for uploading to GCP which is important for one of our solutions.

As a workaround we'll now use a google-sdk docker image and utilize the CLI - but ideally this plugin with the GCP upload plugin would work

Just to set expectations - is this something that would be quick to implement?

Happy to hear your thoughts on that! :)

**Comment by rsandell** [comment]
I don't know enough about this plugin to know if this is possible to implement or not.
I only joined as a maintainer to try to keep dependencies up to date so that it doesn't get blocked by those types of issues.

It is better to ping the original maintainers for these kind of request.

**Comment by dbnicholson** [comment]
It seems to me the way to keep backwards compatibility is:

* Keep the project ID field so that downstream consumers can rely on it.
* Provide a field for a credential ID like every other credential provider. I personally always use stable credential IDs so they're self describing in pipelines and freestyle job definitions.
* If the credential ID is left blank, maybe use the project ID. But honestly I don't see why this provider wouldn't fill a random ID like every other provider.

**Comment by jtnord** [comment]
should be implemented in the referenced PR, closing.
