### ISSUE TITLE
Use standard databinding to retrieve the json key from user

### ISSUE THREAD

**Issue by jpigree** [jenkinsci/google-oauth-plugin#47]
Hi. I am using the "Jenkins Configuration as Code Plugin" to configure credentials into my jenkins.

However, I can't find a way to make it work with this plugin credential because it uses a FileStream as input:
=> https://github.com/jenkinsci/google-oauth-plugin/issues/5#issuecomment-393128560
=> https://github.com/jenkinsci/configuration-as-code-plugin/issues/785

Weirdly enough, when I look at the API generated by the JCasC plugin, it looks like I have to send a string.
![JCasC_API_doc](https://user-images.githubusercontent.com/3977280/54860070-e5867b00-4cb8-11e9-814b-079da53e55c5.png)

With all other credentials I used, it is possible to upload secrets as strings.
Would it be possible to fix this?

Thanks

**Comment by jpigree** [comment]
@timja

**Comment by stephenashank** [comment]
Hi @jpigree, thanks for filing this. We're aware of this issue as it is blocking DSL pipeline support for the GKE plugin (https://github.com/jenkinsci/google-kubernetes-engine-plugin/issues/24). I'm currently reviewing #19 which should address this, as you will be able to provide the SecretBytes directly rather than a filename. See #6 as that might be helpful in the meantime.

**Comment by jpigree** [comment]
Hi @stephenashank. Thank you for your quick answer. Great, it is nearly fixed.

The issue https://github.com/jenkinsci/google-oauth-plugin/issues/6 is interesting but, in my case, I need this credential only for the google-storage-plugin. So, I already know what to do to use it.

Thanks :)

**Comment by jpigree** [comment]
Just another question, Is there an advantage to use this credential type over a simple "secret file" one to store the service account?

When I looked at #6, I don't see any.

Also, should I close this ticket? There is a PR but no Github issue.

**Comment by stephenashank** [comment]
I suspect the primary advantage is that this credential is specific to oauth for other Google services and is leveraged by our other plugins. See this guide from the credentials-plugin on when it makes sense to create a new type of Credentials: [Implementing a New Credentials Type](https://github.com/jenkinsci/credentials-plugin/blob/master/docs/implementation.adoc#implementing-a-new-credentials-type). I think this satisfies the criteria under "If I am using a token to authenticate with the service..." because this token will only be used with GCP.

I'll go ahead and close this issue as a duplicate given that it sounds like the work tracked to similar issues will address your needs in this issue. Just wanted to give you a chance to respond and make sure that was the case.

**Comment by jpigree** [comment]
Yes, it is a duplicate. Thank you for your help and for the way you handled this issue.
I am waiting eagerly for the fix to be released. :)
