### ISSUE TITLE
The plugin seems incompatible with JCASC

### ISSUE THREAD

**Issue by devilmind81** [jenkinsci/google-oauth-plugin#82]
Hi All,
I'm using jcasc to configure my jenkins at bootstrap.
In my scenario I have a pipeline that is building a code on Google CloudBuild so I need to use this plugin to set the google credentials in order to call the google API.
I'm able to install the google oauth plugin  correctly from Jenkins Plugin Manager and I'm able to use it to build on the cloud when jenkins is up and running but my target is to have all configured as code.
So, the problem  is that I cannot export the correct jcasc configuration of my google oauth plugin from jcasc because when I try to do it in the download configuration section I'm obtainig the issue:

` googleRobotPrivateKey:
          module: |-
            FAILED TO EXPORT
            com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials#module: No configurator found for type class com.google.jenkins.plugins.credentials.oauth.GoogleRobotCredentialsModule`

At the same time I'm not able to found the way to implement  directly into jcasc yml the configuration of my google credentials as code because I'm not found a tutorial or guidilines that explains me the correct syntax to do that.

Can you help me on this please?
Otherwise can you address me on how to reach my target please?

Thanks in advance to all.

**Comment by stephenashank** [comment]
Hi @devilmind81, thanks for raising this issue.
Please see this example jcasc config which we use to test: https://github.com/jenkinsci/google-oauth-plugin/blob/develop/src/test/resources/com/google/jenkins/plugins/credentials/oauth/json-service-account-config.yml

Rather than putting the base64 encoded secret directly in your configuration file, look at this documentation for handling secrets and choose a solution which works best for your circumstance: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc

We have an issue to track improvements to documentation, #71. We welcome external contributions for issues like this.

Let me know if you have any other questions, or if you're still encountering this error.

**Comment by devilmind81** [comment]
Hi @stephenashank ,
thanks for your suggestion, I have followed your instruction and I'm able to have it working now.
I have been put the the base64 encoded secret directly in my configuration file and all is working as expected.

Thanks a lot

**Comment by lcsfreire** [comment]
Hello,
we have the same issue and the proposed configuration doesn't solve the problem for us. This is what we have in place: 
credentials:
  system:
    domainCredentials:
      - credentials:
           - googleRobotPrivateKey:
                    projectId: "XXXX"
                    serviceAccountConfig:
                      json:
                        filename: "ZZZZ.json"
                        secretJsonKey: "YYYYYYY"

**Comment by lukesaint** [comment]
This worked for me in a Jinja/Ansible template:

```
credentials:
  system:
    domainCredentials:
    - credentials:
      - googleRobotPrivateKey:
          projectId: "your-project-id"
          serviceAccountConfig:
              json:
                secretJsonKey: "{{ lookup('file', '../service-account-key.json') | b64encode }}"
```
